# Generated by Django 4.2.3 on 2023-07-15 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pedidos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_colores_producto_medidas'),
        ('pedidos', '0004_alter_cliente_celular_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[pedidos.models.validar_dni], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.presentacion', verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(editable=False, max_length=10, verbose_name='Número de pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Total'),
        ),
    ]
