# Generated by Django 4.2.2 on 2023-06-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_color_medida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=300, verbose_name='Slug')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.marca')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
