# Generated by Django 4.2.2 on 2023-06-15 01:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_color_options_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='titulo', unique=True),
        ),
    ]
