# Generated by Django 4.2.2 on 2023-06-15 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_imagen_options_remove_imagen_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.color')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.medida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Presentación de producto',
                'verbose_name_plural': 'Presentaciones de productos',
                'db_table': 'presentacion',
            },
        ),
    ]
