# Generated by Django 4.2.3 on 2023-07-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(through='productos.Presentacion', to='productos.color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='medidas',
            field=models.ManyToManyField(through='productos.Presentacion', to='productos.medida'),
        ),
    ]
